# Generated by Django 5.2.7 on 2025-10-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='guruh',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='kitob_soni',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
