# Generated by Django 5.2.7 on 2025-10-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_talaba_guruh_alter_talaba_kitob_soni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='kitob_soni',
            field=models.PositiveIntegerField(),
        ),
    ]
