# Generated by Django 5.2.7 on 2025-10-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_talaba_kitob_soni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kutubxonachi',
            name='ish_vaqti',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='muallif',
            name='tugilgan_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
